# Generated by Django 4.0.6 on 2023-02-15 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=244)),
                ('kategori', models.CharField(choices=[('makanan', 'Makanan'), ('minuman', 'Minuman')], default='makanan', max_length=12)),
                ('harga', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rekening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_rekening', models.CharField(choices=[('tabungan', 'Tabungan'), ('giro', 'Giro')], max_length=12)),
                ('nomer_rekening', models.CharField(max_length=7, unique=True)),
                ('saldo', models.FloatField()),
                ('tanggal_join', models.DateField(auto_now_add=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('transfer', 'Transfer')], default='transfer', max_length=9)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_from', to='siswa.rekening')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_to', to='siswa.rekening')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(max_length=244)),
                ('tanggal_lahir', models.DateField()),
                ('profile', models.ImageField(default=False, null=True, upload_to='media/%Y/%m/%d/')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_sebelum', models.FloatField()),
                ('saldo_sesudah', models.FloatField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('rekening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.rekening')),
                ('transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siswa.transaction')),
            ],
        ),
    ]
